title: Wilder Journal
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/journal-content" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

repository: "https://github.com/Platoniq/journal-content"
logo: media/logo-platoniq_xxss.jpg
twitter:
  username: platoniq
  card: summary_large_image

# Build settings
theme: jekyll-theme-platoniq-journal
timezone: ES
permalink: /:categories/:title/

collections:
  authors:
    output: true
  journals:
    output: true
    permalink: :path

# Plugin Config
languages: ["en", "es", "ca"]

jekyll-archives:
  enabled:
    - categories
  layout: "archive/category"
  permalinks:
    category: "/category/:name/"

# Document defaults
defaults:
  - scope:
      path: ""
      type: ""
    values:
      layout: "default"
  - scope:
      type: journals
    values:
      layout: "journal"
      author: "platoniq"
  - scope:
      type: authors
    values:
      layout: "author"
  - scope:
      type: posts
    values:
      layout: "article"
      author: "anon"

  - scope:
      path: "_posts/*/blue-prints"
      type: posts
    values:
      categories: "blue-prints"
  - scope:
      path: "_posts/*/deep-dives"
      type: posts
    values:
      layout: "articles/deep_dive"
      categories: "deep-dives"
  - scope:
      path: "_posts/*/interviews"
      type: posts
    values:
      categories: "interviews"
  - scope:
      path: "_posts/*/papers"
      type: posts
    values:
      categories: "papers"
  - scope:
      path: "_posts/journal-01/*"
      type: posts
    values:
      journal-num: 1
      tags: "journal_one"
  - scope:
      path: "_posts/journal-02/*"
      type: posts
    values:
      journal-num: 2
      tags: "journal_two"
  - scope:
      path: "media"
    values:
      media: true

exclude: [Gemfile, Gemfile.lock, README.md, LICENSE.txt, .editorconfig]
