title: Wilder Journal
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/journal" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: jekyll-theme-platoniq-journal
destination: ./build
# plugins:
#  - jekyll-feed

permalinks: pretty

collections:
  articles:
    output: true
    permalink: :categories/:title
  authors:
    output: true
  journals:
    output: true
    permalink: :path


permalinks: pretty

defaults:
  - scope:
      path: ""
      type: ""
    values:
      layout: "default"
  - scope:
      type: journals
    values:
      layout: "journal"
      author: "platoniq"
  - scope:
      type: authors
    values:
      layout: "author"
  - scope:
      path: "_articles"
      type: articles
    values:
      layout: "article"
      author: "anon"
  - scope:
      path: "_articles/*/case-studies"
      type: articles
    values:
      category: "case-studies"
  - scope:
      path: "_articles/*/deep-dives"
      type: articles
    values:
      layout: "articles/deep_dive"
      category: "deep-dives"
  - scope:
      path: "_articles/*/interviews"
      type: articles
    values:
      category: "interviews"
  - scope:
      path: "_articles/*/papers"
      type: articles
    values:
      category: "papers"
  - scope:
      path: "_articles/journal-01/*"
      type: articles
    values:
      journal-num: 1
  - scope:
      path: "_articles/journal-02/*"
      type: articles
    values:
      journal-num: 2
