title: Wilder Journal by Platoniq
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # "/journal-content" # the subpath of your site, e.g. /blog
url: "http://next.journal.platoniq.net" # the base hostname & protocol for your site, e.g. http://example.com
analytics_id: G-0N0TWKN871

repository: "https://github.com/Platoniq/wilder-journal-next"
logo: media/logo-platoniq_xxss.png
twitter:
  username: platoniq
  card: summary_large_image

# Build settings
theme: jekyll-theme-platoniq-journal
timezone: ES

collections:
  archives:
    output: true
    custom_permalink_placeholders: ["locale", "volume-uid", "category", "uid"]
    permalink: /:locale/:volume-uid/:category/
  articles:
    output: true
    custom_permalink_placeholders: ["locale", "volume-uid", "category","uid"]
    permalink: /:locale/:volume-uid/:category/:uid/
  authors:
    output: false
  call_to_actions:
    output: false
  volumes:
    output: true
    custom_permalink_placeholders: ["locale", "uid"]
    permalink: /:locale/:uid/
  pages:
    output: true
    custom_permalink_placeholders: ["locale", "uid"]
    permalink: /:locale/:uid/
  stickers:
    output: false
  sticker_packs:
    output: true
    custom_permalink_placeholders: ["locale", "volume-uid"]
    permalink: /:locale/:volume-uid/stickers/

# Document defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      locale: es
  - scope:
      path: "*/en/*"
    values:
      locale: "en"
  - scope:
      path: "*/es/*"
    values:
      locale: "es"
  - scope:
      type: volumes
    values:
      layout: "journal"
      author: "platoniq"
  - scope:
      type: authors
    values:
      layout: "author"
      author: "platoniq"
  - scope:
      type: articles
    values:
      layout: "article"
      author: "anonymous"
  - scope:
      type: sticker_packs
    values:
      layout: "sticker_pack"
      author: "anonymous"
  - scope:
      type: pages
    values:
      layout: "page"
      author: "platoniq"
  - scope:
      path: "media"
    values:
      media: true

exclude: [Gemfile, Gemfile.lock, README.md, LICENSE.txt, .editorconfig]


# Plugins
plugins:
  - jekyll-target-blank

target-blank:
  add_css_classes: link-external
  noopener: true
  noreferrer: true
  rel: nofollow
