---
permalink: cms/config.yml
layout: none
---
# NetlifyCMS Docs Configuration Options: https://www.netlifycms.org/docs/configuration-options/

backend:
  name: git-gateway
  # repo: agustibr/journal-content
  branch: main
locale: es
local_backend: true

media_folder: "media"

publish_mode: editorial_workflow # Enable drafts

i18n:
  # Required and can be one of multiple_folders, multiple_files or single_file
  # multiple_folders - persists files in `<folder>/<locale>/<slug>.<extension>`
  # multiple_files - persists files in `<folder>/<slug>.<locale>.<extension>`
  # single_file - persists a single file in `<folder>/<slug>.<extension>`
  structure: multiple_folders

  # Required - a list of locales to show in the editor UI
  locales: &locales [en, es]

  # Optional, defaults to the first item in locales.
  # The locale to be used for fields validation and as a baseline for the entry.
  default_locale: en

collections:
  - name: "journals"
    label: "Journals"
    folder: "_journals/"
    i18n:
      structure: multiple_folders
      locales: *locales
    create: true
    delete: true
    editor:
      preview: true
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "journal", i18n: duplicate }
      - { label: "Journal volume number", name: "journal-num", widget: "number", default: 0, value_type: "int", min: 1, max: 101, step: 1, i18n: duplicate }
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - { label: "Publish Date", name: "date", widget: "date", i18n: duplicate }
      - { label: "Slug", name: "uid", widget: "string", i18n: duplicate }
      - label: "Cover image"
        name: "cover"
        widget: "object"
        summary: "Summary of the field"
        fields:
          - {
            label: "Hero Image",
            hint: Big cover image,
            name: "path",
            widget: "image",
            choose_url: true,
            default: "/media/covers/heros/none.png",
            media_library: { config: { multiple: false },
            i18n: translate },
            media_folder: "/media/covers/heros"
            }
          - {
              label: "Thumbnail Image",
              hint: Small image used in lists,
              name: "thumbnail",
              widget: "image",
              choose_url: true,
              default: "/media/covers/thumbnails/none.png",
              media_library: { config: { multiple: false } },
              media_folder: "/media/covers/thumbnails",
              i18n: duplicate
              }
          - { label: "Image alt text", name: "alt", widget: "string", i18n: translate }
          - { label: "Image Credits", name: "credits", widget: "string", i18n: translate }
          - { label: "Image Caption", name: "caption", widget: "string", i18n: translate }

  - name: "articles"
    label: "Articles"
    folder: "_posts/"
    i18n:
      structure: multiple_folders
      locales: *locales
    create: true # Allow users to create new documents in this collection
    slug: "{{uid}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: true
    fields: # The fields for each document, usually in front matter
      - { label: "Layout", name: "layout", widget: "hidden", default: "article" }
      - { label: "Title", name: "title", widget: "string", i18n: translate }
      - { label: "Publish Date", name: "date", widget: "datetime", i18n: duplicate }
      - { label: "Slug", name: "uid", widget: "hidden", i18n: duplicate, default: "{{slug}}" }
      - {
          label: "Author",
          name: "author",
          widget: "relation",
          collection: "authors",
          display_fields: [name],
          search_fields: [name],
          value_field: "uid",
          i18n: duplicate
        }
      - {
          label: "Journal",
          name: "journal-uid",
          widget: "relation",
          collection: "journals",
          display_fields: [title],
          search_fields: [title],
          value_field: "uid",
          i18n: duplicate
        }
      - { label: "Body", name: "body", widget: "markdown", i18n: true }
  - name: "authors"
    label: "Authors"
    folder: "_authors/"
    slug: "{{uid}}"
    i18n:
      structure: multiple_files
      locales: *locales
    create: true
    editor:
      preview: true
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "author" }
      - { label: "Short Name", name: "uid", widget: "string", i18n: duplicate }
      - { label: "Diplay Name", name: "name", widget: "string", i18n: duplicate }
      - {
          label: "Featured Image",
          hint: The author's avatar,
          name: "image_url",
          widget: "image",
          choose_url: true,
          default: "/media/authors/none.png",
          media_library: { config: { multiple: false },
          i18n: duplicate }
      }
      - { label: "Position", name: "position", widget: "string", i18n: translate }
      - { label: "Body", name: "body", widget: "markdown", i18n: translate }
  - name: "pages"
    label: "Pages"
    editor:
      preview: false
    files:
      - label: "About Page"
        name: "about"
        file: "_pages/en/about.md"
        fields:
          - {
              label: "Title",
              name: "title",
              widget: "hidden",
              default: "about",
            }
          - {
              label: "Layout",
              name: "layout",
              widget: "hidden",
              default: "about",
            }
          - { label: "Body", name: "body", widget: "markdown" }
  - name: "config"
    label: "Config"
    editor:
      preview: false
    files:
      - label: "Navigation"
        name: "navigation"
        file: "_data/navigation.yml"
        fields:
          - label: "Navigation Items"
            name: "items"
            widget: "list"
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Link, name: link, widget: string }
